server:
  port: 8082
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/
spring:
  application:
    name: order-fegin
  thymeleaf:
    encoding: utf-8
    prefix: classpath:/templates/
    suffix: .html
    cache: false

feign:
  httpclient:
    enabled: true


  hystrix:
    enabled=false: